name: 510004015-sync
on:
  schedule:
    - cron: '20 1 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-510004015-Quantumult_X
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync 510004015-Quantumult_X
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/510004015/Quantumult_X.git"
          source_branch: "main"
          destination_branch: "510004015"
          github_token: ${{ secrets.PAT }}
