name: WeiRen0-sync
on:
  schedule:
    - cron: '20 0 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-WeiRen0-Scripts
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync WeiRen0-Scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/WeiRen0/Scripts.git"
          source_branch: "main"
          destination_branch: "WeiRen0"
          github_token: ${{ secrets.PAT }}
